import UUID4 from 'uuid/v4';

export interface IMovie {
  id?: UUID4,
  Title?: string,
  Year?: string,
  Rated?: string,
  Released?: string,
  Runtime?: string,
  Genre?: string,
  Director?: string,
  Writer?: string,
  Actors?: string,
  Plot?: string,
  Language?: string,
  Country?: string,
  Awards?: string,
  Poster?: string,
  Ratings?: Array<{}>,
  Metascore?: string,
  imdbRating?: string,
  imdbVotes?: string,
  imdbID?: string,
  Type?: string,
  DVD?: string,
  BoxOffice?: string,
  Production?: string,
  Website?: string,
  Response?: string,
  videoURL?: string,
}
